#!/usr/bin/env python

from sh import mkdir, wget, unzip, rm
import os


mkdir("-p", "translations")
os.chdir("translations")

wget("http://www.census.gov/geo/maps-data/data/docs/gazetteer/Gaz_counties_national.zip")
unzip("Gaz_counties_national.zip")
wget("http://www.census.gov/geo/maps-data/data/docs/gazetteer/Gaz_places_national.zip")
unzip("Gaz_places_national.zip")
rm("*zip")

os.chdir("..")
