#!/usr/bin/env python

from sh import mkdir, wget

import sys
import sh
import us
import os


URL = "http://www.census.gov/geo/maps-data/data/docs/gazetteer/{type}_list_{fips}.txt"

for state in us.states.STATES:
    for t in ("counties", "2010_place"):
        fips = state.fips
        url = URL.format(type=t, fips=fips)
        path = "translations/%d/%s" % (int(fips), t)
        cwd = os.getcwd()
        mkdir('-p', path)
        os.chdir(path)
        try:
            wget(url)
        except sh.ErrorReturnCode_8:
            sys.stderr.write("[ err ] 404: " + url + "\n")
            sys.stderr.flush()

        os.chdir(cwd)
